### ISSUE TITLE
climr webpage not deploying. 

### ISSUE THREAD

**Issue by cmahony** [bcgov/climr#272]
@CeresBarros we've done the v0.1 release but the website is not deploying. github pages is saying it's deployed but the new site is not there. i've checked the index file in the repo on main and it is fine. help?

**Comment by CeresBarros** [comment]
I'm not entirely sure why the deployed pages do not show the latest version -- still working on that.
But there were several other issues -- notably documentation problems that were causing package check failures -- that I addressed in #273 

test coverage checks on #273 PR still failed -- I'm not sur why either -- but everything else passed, so I'm merging. The merge will trigger another round of tests and I'll be able to poke pkgdown then.

**Comment by CeresBarros** [comment]
The newly deployed page is fixed. The issue was the version number being wrong and pointing to a development (not the release) version. So `pkgdown` was rendering to `docs/rev/`:

from [https://pkgdown.r-lib.org/articles/how-to-update-released-site.html](https://pkgdown.r-lib.org/articles/how-to-update-released-site.html):
> In this mode, [pkgdown::build_site()](https://pkgdown.r-lib.org/reference/build_site.html), consults DESCRIPTION to learn the package’s version number. For a development version number, the rendered site is written to docs/dev/. For a released version number, the site is written to docs/. (There are also other signals to alert users that they are reading documentation for a dev version vs. a released version.)

**Comment by cmahony** [comment]
@CeresBarros thanks a million for your help and many fixes. what is your advice on which mode we should go with? i don't have a good sense of the pros and cons.

**Comment by cmahony** [comment]
ok, that helps. thanks! If those pros/cons were for auto mode, i vote to stick with "release" mode. we are encouraging users to subscribe to release notifications, and so i would like to be able to update the website easily without triggering a release notification. i don't see a need for users to see a dev website; they could use the package documentation in devl. 
that's vote 1 of 3. let me know yours.

**Comment by CeresBarros** [comment]
Yes the pros/cons were for `mode: auto`

No strong feelings here. Because this package is solely on GH, it does make sense for the documentation to be in line with the current state of the `main` branch -- regardless of whether it corresponds to a release or not. So totally fine, in my view, to keep `mode: release`, which is btw a very misleading terminology as recognised in `pkgdown` doc:

> If unspecified, the default is mode: release, which results in a single pkgdown site. Despite the name, this single site reflects “the current package state”, which could be either a released state or a development state.

Please remember that it still seems that not updating the version number in DESCRIPTION was causing the site not to be updated. So we'll still need to be mindful about bumping versions in DESCRIPTION.

**Comment by cmahony** [comment]
Ok that all makes sense. yes, the v number in description was a key oversight!. thanks again for your help today.

**Comment by cmahony** [comment]
resolved.
